// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Admin__AdminLayoutController from "././admin/admin_layout_controller"
application.register("admin--admin-layout", Admin__AdminLayoutController)

import Admin__ArrayManagerController from "././admin/array_manager_controller"
application.register("admin--array-manager", Admin__ArrayManagerController)

import Admin__AuthLayoutController from "././admin/auth_layout_controller"
application.register("admin--auth-layout", Admin__AuthLayoutController)

import Admin__DashboardLayoutController from "././admin/dashboard_layout_controller"
application.register("admin--dashboard-layout", Admin__DashboardLayoutController)

import Admin__DropdownController from "././admin/dropdown_controller"
application.register("admin--dropdown", Admin__DropdownController)

import Admin__FormController from "././admin/form_controller"
application.register("admin--form", Admin__FormController)

import Admin__ImageCropperController from "././admin/image_cropper_controller"
application.register("admin--image-cropper", Admin__ImageCropperController)

import Admin__NotificationController from "././admin/notification_controller"
application.register("admin--notification", Admin__NotificationController)

import Admin__PageSorterController from "././admin/page_sorter_controller"
application.register("admin--page-sorter", Admin__PageSorterController)

import Admin__PasswordToggleController from "././admin/password_toggle_controller"
application.register("admin--password-toggle", Admin__PasswordToggleController)

import Admin__PodSorterController from "././admin/pod_sorter_controller"
application.register("admin--pod-sorter", Admin__PodSorterController)

import Admin__TinymceController from "././admin/tinymce_controller"
application.register("admin--tinymce", Admin__TinymceController)

import Admin__PodPreviewController from "././admin/pod_preview_controller"
application.register("admin--pod-preview", Admin__PodPreviewController)
